#!/bin/bash

# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

# Generate Android.bp
echo "// DO NOT EDIT THIS FILE MANUALLY" > Android.bp

for key in $(grep -o :\.\*override keys.mk | sort -u) :gmscompat_lib; do
    echo "" >> Android.bp
    echo "android_app_certificate {" >> Android.bp
    echo "    name: \"${key:1}\"," >> Android.bp
    echo "    certificate: \"${key:1}\"," >> Android.bp
    echo "}" >> Android.bp
done

# Generate platform keys
for key in ../../../build/make/target/product/security/*.pk8; do
    ./make_key.sh $(basename "$key" .pk8)
done

# Generate override keys
for key in $(grep -o :\.\*override keys.mk | sort -u) :gmscompat_lib; do
    ./make_key.sh "${key:1}" 4096
done

# --- Bluetooth certificate override replacement ---
SRC_PEM="bluetooth.x509.pem"
DST_PEM="com.android.bluetooth.certificate.override.x509.pem"

SRC_PK8="bluetooth.pk8"
DST_PK8="com.android.bluetooth.certificate.override.pk8"

# Replace X509 certificate
if [ -f "$SRC_PEM" ]; then
    cp -f "$SRC_PEM" "$DST_PEM"
else
    echo "Warning: Bluetooth PEM source '$SRC_PEM' not found, skipping"
fi

# Replace PK8 private key
if [ -f "$SRC_PK8" ]; then
    cp -f "$SRC_PK8" "$DST_PK8"
else
    echo "Warning: Bluetooth PK8 source '$SRC_PK8' not found, skipping"
fi
